---
abstract: 'Simple yet Powerful Controller Class dispatcher for Dancer'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Dispatcher
requires:
  Dancer: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dancer-Plugin-Dispatcher
  homepage: http://ana.io/
  repository: http://github.com/alnewkirk/Dancer-Plugin-Dispatcher.git
version: 0.12
